"""Type stubs for the compiled `_hl7pet` extension module.

Mirrors specs/6000-python-bindings-automation/contracts/python-api.md.
"""

from typing import Any

class LocatedValue:
    value: str
    line: int

class Hl7PetError(Exception): ...
class Hl7ScanError(Hl7PetError): ...
class Hl7PathError(Hl7PetError): ...
class Hl7QueryError(Hl7PetError): ...
class Hl7ProfileError(Hl7PetError): ...

def get_value(message: str, path: str) -> list[list[str]] | None: ...
def get_value_hierarchy(
    message: str, path: str, profile: dict[str, Any], build_hierarchy: bool = True
) -> list[list[str]] | None: ...
def get_first_value(message: str, path: str) -> str | None: ...
def get_value_located(
    message: str, path: str
) -> list[list[LocatedValue]] | None: ...
def get_first_value_located(message: str, path: str) -> LocatedValue | None: ...
def get_values(
    message: str, paths: list[str]
) -> list[list[list[str]] | None]: ...
